"""Pydantic response models — the contract the frontend codes against."""

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


class FindingSeverity(str, Enum):
    NORMAL = "normal"
    ABNORMAL = "abnormal"
    CRITICAL = "critical"


class ClinicalFinding(BaseModel):
    parameter: str = Field(..., description="e.g. 'Hemoglobin', 'LDL Cholesterol'")
    value: str = Field(..., description="Reported value as found in the document, e.g. '10.2 g/dL'")
    reference_range: str | None = Field(default=None, description="Normal range, if stated in the report")
    severity: FindingSeverity
    plain_language_explanation: str = Field(
        ..., description="Jargon-free explanation of what this finding means"
    )


class AnalysisResponse(BaseModel):
    analysis_id: str
    session_id: str
    file_name: str
    summary: str = Field(..., description="Plain-language overview of the whole report")
    findings: list[ClinicalFinding] = Field(default_factory=list)
    overall_severity: FindingSeverity
    recommended_action: str = Field(
        ..., description="e.g. 'Routine follow-up' or 'Consult a physician promptly'"
    )
    disclaimer: str = Field(
        default=(
            "This analysis is generated by an AI system for informational purposes only "
            "and does not constitute medical advice. Always consult a qualified healthcare "
            "professional for diagnosis and treatment decisions."
        )
    )
    provider_used: str
    created_at: datetime

    model_config = {"from_attributes": True}


class ChatResponse(BaseModel):
    analysis_id: str
    question: str
    answer: str
    provider_used: str


class AnalysisHistoryItem(BaseModel):
    analysis_id: str
    file_name: str
    overall_severity: FindingSeverity
    summary: str
    created_at: datetime


class SessionHistoryResponse(BaseModel):
    session_id: str
    analyses: list[AnalysisHistoryItem] = Field(
        default_factory=list, description="Most recent analyses for this session, newest first"
    )


class HealthResponse(BaseModel):
    status: str = "ok"
    app_name: str
    version: str
    gemini_configured: bool
    openrouter_configured: bool


class ErrorResponse(BaseModel):
    code: str
    message: str
    details: dict = Field(default_factory=dict)
